### ISSUE TITLE
Version 2.0.0 won't compile on Delphi 10.3 Rio

### ISSUE THREAD

**Issue by Scytheroid** [danieleteti/loggerpro#101]
The problem is in `TLogItemRendererJSONL.RenderLogItem`. `TJSONObject.AddPair` has far less overload options than newer Delphi releases.

Because of that, the last line of the function, where `ALogItem.ThreadID` is being appended, throws compilation error.

```
[dcc32 Error] LoggerPro.JSONLFileAppender.pas(138): E2250 There is no overloaded version of 'AddPair' that can be called with these arguments
```
